### ISSUE TITLE
Suggestions for Titles

### ISSUE THREAD

**Issue by georgestevens99** [ThatDeveloperDad/system-framework#3]
I just printed out all your docs under the Table of Contents.

Here are suggestions for a couple of your document titles:

Detailed Design Pt 1:  I'd call this "Detailed Design -- Contract Design". (or Detailed Design -- Data and Service Contract Design)

Detailed Design pt 2:  I'd call this "Detailed Design -- Component Interaction Design."  The the term "Interaction Design" (sometimes called IxD) is widely used in UX, thus just naming Detailed Design Pt2 as "Interaction Design" could cause confusion.  Plus JL uses the concept of "Composable Design" which is based on a Component Oriented Architecture.   Thus Component Interaction Design fits in well.  Although, perhaps "Composable Design" could somehow fit in that title.

Thanks,
George Stevens

**Comment by robmccrady** [comment]
Excellent suggestions.  I'll implement these immediately.
